### ISSUE TITLE
[SUGGESTION] Filter

### ISSUE THREAD

**Issue by theaweful** [Fennecai/Aperture-Continued#18]
**Describe the solution you'd like**
Is some sort of filtering mechanic for the diversity vent possible? Like making gels always go right at an intersection and cubes go left.

**Describe alternatives you've considered**
Another vent in the Diversity vent section that will "scan" the object and separate the items based on what they are. [Such as this].(https://theportalwiki.com/wiki/File:Pneumatic_Diversity_Vent_E3_Promo.png)

**Comment by CrishNate** [comment]
Yes, it does have filter option. You can edit filter on specific tubes that have several passes. It must have something like a blue ball (as I remmember), that you can click on. Filter menu will appear, where you can edit tube filter settings.

**Comment by Fennecai** [comment]
It does? er- did, anyhow? I just recently removed the t and x junction tubes temporarily due to a crash that happens with infinite loops, but if you can explain your code to me in detail for how the vents even choose paths randomly, to begin with; I might be able to fix that issue and re-implement this awesome feature.
